dist: bionic

language: node_js
node_js:
  - 14.16.0

cache:
  yarn: true

env:
  global:
    - PATH="$HOME/.yarn/bin:$PATH"
    - YARN_VERSION="1.9.4"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "${YARN_VERSION}"

install:
  - yarn install --frozen-lockfile

jobs:
  include:
    # Install dependencies and save them to the Travis cache
    - stage: "Prepare cache"
      # Don't run `script`, just install dependencies
      before_script: skip
      script: skip
    # Run tests
    - stage: "Test"
      name: "Lint"
      script: yarn run lint
    - name: "Type Checking"
      script: yarn run typecheck
    - name: "Unit Tests"
      script: yarn run test:unit
    - stage: "Publish to registry"
      if: tag =~ ^v
      script: skip
      deploy:
        provider: npm
        email: open-source@goodeggs.com
        api_token:
          secure: "ZsR2kJqwSpNSmT2SwM55MMx4Hnmwk6eslpjhcTdUiRN5VF5zTU4YFz1REjMWaInkjKQCgvGgzRckn5gDOV11bYZB1vFCh8wSgIwrH6Jbo6j1uSe9Xe2m00HJwtbbEZOn4QqiepdSASg4LpBDXv8g+WgmE9/NoCNshvdwUwNTmF8="
        skip_cleanup: true
        on:
          tags: true
          all_branches: true
