dist: xenial

language: node_js
node_js:
  - 14.16.0

cache:
  yarn: true

env:
  global:
    - PATH="$HOME/.yarn/bin:$PATH"
    - YARN_VERSION="1.9.4"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "${YARN_VERSION}"

install:
  - yarn install --frozen-lockfile
  - yarn run build
  - yarn link

jobs:
  include:
    # Install dependencies and save them to the Travis cache
    - stage: "Prepare cache"
      # Don't run `script`, just install dependencies
      before_script: true
      script: true
    # Run tests
    - stage: "Test"
      name: "Lint"
      script: yarn run lint
    - name: "Unit Tests"
      script: yarn run test
      # TODO(ndhoule): Enable when this repository is made public.
      # after_success:
      #   - bash <(curl -s https://codecov.io/bash)
    - stage: "Publish to registry"
      if: tag =~ ^v
      script: echo "Publishing to npm registry..."
      deploy:
        provider: npm
        email: open-source@goodeggs.com
        api_key: $NPM_AUTH
        skip_cleanup: true
        on:
          all_branches: true